export const TIMER_START = 'TIMER_START';
export const TIMER_RESET = 'TIMER_RESET';
export const TIMER_END = 'TIMER_END';
export const TIMER_DECREMENT = 'TIMER_DECREMENT';

export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_LOADING = 'FETCH_QUESTION_LOADING';

export const ADVANCE_STEP = 'ADVANCE_STEP';
export const CALCULATE_CURRENT_SCORE = 'CALCULATE_CURRENT_SCORE';
export const UPDATE_HIGHEST_SCORE = 'UPDATE_HIGHEST_SCORE';

