export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';
export const FETCH_QUESTION_LOADING = 'FETCH_QUESTION_LOADING';
export const SAVE_ALREADY_ASKED_QUESTIONS = 'SAVE_ALREADY_ASKED_QUESTIONS';

export const ADVANCE_STEP = 'ADVANCE_STEP';
export const RESET_STEP = 'RESET_STEP';
export const RESET_CURRENT_SCORE = 'RESET_CURRENT_SCORE';
export const RESET_HIGHEST_SCORE = 'RESET_HIGHEST_SCORE';

export const CALCULATE_CURRENT_SCORE = 'CALCULATE_CURRENT_SCORE';
export const UPDATE_HIGHEST_SCORE = 'UPDATE_HIGHEST_SCORE';

